### PR TITLE
Issue/178 Make cuzzle optional

### PR DESCRIPTION
**Pull request by Avariya**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no, i guess
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/csarrazi/CsaGuzzleBundle/issues/178
| License       | Apache License 2.0

### CODE REVIEW

**Comment by csarrazi** [comment]
Great! Nothing much to say. Just make sure that this doesn't break the Twig template.

**Comment by Avariya** [comment]
https://github.com/csarrazi/CsaGuzzleBundle/blob/344fd00eca4f7cf144e2cd8deb6dcd015d00f9a6/src/Resources/views/Calls/list.html.twig
We have check ` {% if call.curl is defined %} `.
Tested earlier if curl is not defined - whole curl part is not rendered at all. That cool!

**Comment by csarrazi** [comment]
Great!

**Comment by csarrazi** [comment]
Thank you @Avariya !

**Pull request merged**
