### PR TITLE
Make bundle Symfony 3.4 compatible.

### PR DESCRIPTION
**Pull request by bellisk**
| Q             | A
| ------------- | ---
| Bug fix?      | [yes]
| New feature?  | [no]
| BC breaks?    | [no]
| Deprecations? | [no]
| Tests pass?   | [yes]
| Fixed tickets | [none]
| License       | Apache License 2.0

### CODE REVIEW

**Comment by bellisk** [comment]
@csarrazi  Can you merge this and tag it on the 2.x branch please? Thanks!

**Comment by csarrazi** [comment]
Hi, I’m not really fond of this. Version 2.x is now deprecated in favor of version 3.0. If you want to upgrade to Symfony 3.4, you should upgrade to version 3.0 of the bundle.

Did you try upgrading first?

**Comment by bellisk** [comment]
Hi, we're currently unable to upgrade because we can't use PHP 7.1 in production. We're obviously working on that, but we'd like to be able to use 2.x of the bundle without deprecations in the meantime.

**Comment by csarrazi** [comment]
Makes sense. I will merge this, and make a new release.
Thanks for the contribution, @bellisk!

**Comment by bellisk** [comment]
Thank you!

**Comment by csarrazi** [comment]
Done. Tag 2.2.2 released!

**Comment by bellisk** [comment]
Thanks! :D

**Pull request merged**
