### PR TITLE
Add missing LICENSE

### PR DESCRIPTION
**Pull request by Nicofuma**
| Q             | A
| ------------- | ---
| Bug fix?      | [yes]
| New feature?  | [no]
| BC breaks?    | [no]
| Deprecations? | [no]
| Tests pass?   | [yes]
| Fixed tickets | []
| License       | MIT

### CODE REVIEW

**Comment by csarrazi** [comment]
Actually, I'm considering a license change, from MIT to something else (no worries, it will still be permissive, of course).

**Comment by csarrazi** [comment]
The license will most certainly be Apache License 2.0.

**Comment by csarrazi** [comment]
By the way, you chose the wrong folder for the license. There's already a license file in the bundle's meta directory.

**Comment by Nicofuma** [comment]
Right... I missed it

**Comment by csarrazi** [comment]
No problem! ;)

**Pull request closed without merging**
