### PR TITLE
fix twig extension deprecation (since Twig 2.7).

### PR DESCRIPTION
**Pull request by hervems**
| Q             | A
| ------------- | ---
| Bug fix?      | [no]
| New feature?  | [no]
| BC breaks?    | yes]
| Deprecations? | [yes]
| Tests pass?   | [yes]
| Fixed tickets | []
| License       | Apache License 2.0

### CODE REVIEW

**Comment by csarrazi** [comment]
Thanks for the pull request. Are we certain that Twig 1.x is no longer maintained? Do we know when `Twig_SimpleFilter` will be actually removed from Twig? (I suspect Twig 3.x, but I want to confirm).

**Comment by csarrazi** [comment]
Please note that because of the removal of the Twig 1.x dependency, this would be a BC break, hence justifying an upgrade of the bundle's major version.

**Comment by hervems** [comment]
Yes, effectively, it's a BC here, but I think it's a good practice to be up to date, at least, to propose a version without trigger_error message. In my case, we can't pass Travis CI just for that.

**Comment by csarrazi** [comment]
In that case, can you raise the branch alias for `master` to `4.0-dev`?

Thanks

**Comment by hervems** [comment]
Yes, I'm ok for that.
Thanks

**Comment by csarrazi** [comment]
I'll merge this as soon as you update the branch-alias :)

**Comment by csarrazi** [comment]
Thanks @hervems!

**Pull request merged**
