### PR TITLE
Symfony 4 and Flex compatibility

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | n/a
| License       | Apache License 2.0

### CODE REVIEW

**Comment by csarrazi** [comment]
Hi @dunglas, I don’t see how these changes add support for Flex. Did you create a PR in the recipes for this bundle? If you could link the associated PR, that would be great!

**Comment by dunglas** [comment]
I've not created a recipe yet. This PR just allows the bundle to work (currently its broken) but you still need to configure it manually (not sure if it can be automated anyway).

**Comment by csarrazi** [comment]
Thanks @dunglas!

By the way, if you want to add a simple recipe for flex, be my guest! 😉

**Comment by kejwmen** [comment]
@csarrazi could we get a new release including this?

**Comment by csarrazi** [comment]
@kejwmen There is currently some work pending, but there will be a 3.0 release soon.

**Comment by kejwmen** [comment]
thanks!

**Pull request merged**
