### PR TITLE
Fix: Added guzzlehttp/log-subscriber to the require list in composer.json

### PR DESCRIPTION
**Pull request by DemonTPx**
Hi,

A change in version 1.2.4 caused my Symfony app to fail on the dependency injection compile phase with the following exception:

Fatal error: Class 'GuzzleHttp\Subscriber\Log\Formatter' not found in /Users/bert/workspace/core-site/vendor/csa/guzzle-bundle/src/DependencyInjection/Configuration.php on line 61

I figured that the guzzlehttp/log-subscriber dependency was missing, so I've added it.

Cheers,
Bert

### CODE REVIEW

**Comment by JordyMoos** [comment]
+1

**Comment by csarrazi** [comment]
Can you tell me whether release v1.2.5 fixes the issue?

**Comment by micayael** [comment]
+1

**Comment by csarrazi** [comment]
I'm closing the issue as it was fixed in 649c264ff11536409e18eafdff600e97b45fb3c3. The dependency should ony be in the master branch. Thanks, though! :)

**Comment by DemonTPx** [comment]
It's fixed. Thanks! :+1:

**Pull request closed without merging**
