### PR TITLE
Symfony 5 support

### PR DESCRIPTION
**Pull request by rvanlaak**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A
| License       | Apache License 2.0

Allow installing bundle with Symfony 5.0

Appveyor fix borrowed from https://github.com/symfony/symfony/commit/6194c2a96c6c8c35de8929a95a3f498941cd1760

### CODE REVIEW

**Comment by csarrazi** [comment]
Thanks @rvanlaak !

**Comment by rvanlaak** [comment]
You are welcome! Time for some tagging 🎉

**Comment by csarrazi** [comment]
The rationale for this is that Guzzle is not part of the Symfony project, and other projects want to use the middleware, without necessarily fetch every single dependency.

**Comment by rvanlaak** [comment]
@csarrazi is there work to be done before a new minor can get tagged?

**Comment by csarrazi** [comment]
Not really. It's just that I no longer have a personal laptop, so I won't be able to push tags until I find some time to set up something on another machine.

**Comment by rvanlaak** [comment]
Github allows creating tags directly 🎉:

https://github.com/csarrazi/CsaGuzzleBundle/releases/new

**Comment by csarrazi** [comment]
True, but from what I recall, GitHub only creates lightweight tags, and not annotated tags (which are signed and associated to an author). I'll do that in the upcoming days, once I manage to find some time! :)

**Comment by rvanlaak** [comment]
Great! Let us know when you need help 💪

**Comment by Surf-N-Code** [comment]
Sorry to bug you on this, but did you find the time yet? :) @csarrazi

**Comment by rvanlaak** [comment]
@csarrazi can you tag the new version?

**Comment by mvorisek** [comment]
@csarrazi  Can a new tagged release be made to reflect this merged PR?

**Comment by csarrazi** [comment]
New release tagged

**Pull request merged**
