### PR TITLE
Add support for jms serializer to deserialize to model and the usage of paramconverter #30

### PR DESCRIPTION
**Pull request by ajanssen**
What do you think about the solution?

### CODE REVIEW

**Comment by csarrazi** [comment]
That's some great work, and I'll take more time reviewing the code later!

Regardless, I think we should be serializer-agnostic.

As much as possible, I wish to use the Symfony serializer (especially with the many improvements of `v2.7`), as JMS uses the Apache license, which is incompatible with GPLv2 (and there are a few bundles or libraries which are distributed with this license).

At least, we should provide adapters and an interface abstracting both serializers.

Oh yeah! And don't forget to add some tests, later! :)

**Comment by ajanssen** [comment]
Yes, i'm still thinking about how i'm going to do this! i have a some ideas i will try to make them tomorrow! Do you have some ideas about how to make it serializer agnostic (JMS or Symfony etc)?

**Comment by csarrazi** [comment]
Both serializers nearly have the same method signature for serialize and deserialize. Symfony's serializer being the standard, let's use Symfony's `Symfony\Component\Serializer\SerializerInterface`, and create an adapter for JMS Serializer, making the transformation.

```php
<?php

namespace Csa\Bundle\GuzzleBundle\Serializer;

use Symfony\Component\Serializer\SerializerInterface;
use JMS\Serializer\SerializerInterface;

class JmsAdapter implements SerializerInterface
{
    private $serializer;

    public function __construct(JmsSerializerInterface $serializer)
    {
        $this->serializer = $serializer;
    }

    // Implement both serialize() and deserialize() methods here
}
```

**Comment by ajanssen** [comment]
Yes, i think that method will be best! i will try to create an pull request today or tomorrow.

**Comment by csarrazi** [comment]
Could you change your PR to target the `1.3` branch, please? :)

Master will be used for the next major release (`2.0.x`)

**Comment by ajanssen** [comment]
How can i change the PR branch? And is this what you were thinking?

**Comment by csarrazi** [comment]
You can do this by closing the PR, and re-creating it! :)

**Pull request closed without merging**
