### PR TITLE
Fixed Middleware using deprecated StorageAdapterInterface interface.

### PR DESCRIPTION
**Pull request by OwlyCode**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |
| License       | MIT

### CODE REVIEW

**Comment by csarrazi** [comment]
@OwlyCode That's actually normal, and will be the case until version 3.0 of the bundle ;)

Do you actually have issues with the deprecation warning?

**Comment by OwlyCode** [comment]
It was showing in the Symfony deprecation toolbar because we created a custom DoctrineAdapter on our project, we did it this way : 

```php
use Csa\Bundle\GuzzleBundle\GuzzleHttp\Cache\DoctrineAdapter;

class CacheAdapter extends DoctrineAdapter
{
    // do some custom stuff
}
```
And, seeing the deprecation, we changed to :

```php
<?php
use Csa\Bundle\GuzzleBundle\Cache\DoctrineAdapter;
use Csa\Bundle\GuzzleBundle\Cache\StorageAdapterInterface;

class CacheAdapter extends DoctrineAdapter implements StorageAdapterInterface
{
    // do some custom stuff
}
```

But with this code, we end up getting an exception : 

```
Type error: Argument 1 passed to Csa\Bundle\GuzzleBundle\GuzzleHttp\Middleware::cache() must be an instance of Csa\Bundle\GuzzleBundle\GuzzleHttp\Cache\StorageAdapterInterface, instance of My\AppBundle\Cache\CacheAdapter given
```

**Comment by csarrazi** [comment]
OK, LGTM! Thanks @OwlyCode!

**Comment by OwlyCode** [comment]
Thanks @csarrazi !

**Pull request merged**
