### PR TITLE
Refactored History middleware

### PR DESCRIPTION
**Pull request by csarrazi**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #185 #184 #164
| License       | Apache License 2.0

This ticket reverts the changes brought by @jderusse, and drops support for the correlation ID.
At the same time, this request fixes a few issues with error handling, and brings support for displaying curl errors when they happen. This actually makes debugging much easier, when a request is issued in a `try {} catch {}` statement, and does not throw an error.

### CODE REVIEW

**Comment by csarrazi** [comment]
As mentioned in the title, this drops support for matching requests together. In order to prevent request from being duplicated in the profiler panel, middleware which change the request (headers, body, etc.) should have a priority set to a higher value than the history middleware.

**Comment by csarrazi** [comment]
This is actually the main reason why the cache, mock and history middleware have a priority in the minus values. User-defined middleware should *always* have a priority greater or equal to 0.

**Comment by jderusse** [comment]
The main issue with this approach, is that the object request may change not only in a middleware, but it can happens in a handler too (see https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php#L41)

You could test it by disabling the curl extension (which force guzzle to use the StreamHandler which alter the request)

**Comment by csarrazi** [comment]
True. But regardless, the current approach is problematic with any type of cache. Also, this issue should actually be filed as a bug in the Guzzle project.

**Comment by csarrazi** [comment]
The only other solution would be to drop support for stats, as the problem comes from the `add_stats` command, which cannot merge the two requests, when using the stream handler.

What we can do is simply remove support for `add_stats` when the curl extension is not installed.

**Comment by jderusse** [comment]
What was the original reason to remove the correlationId things? (Except it's an ugly hack)

**Comment by csarrazi** [comment]
The correlation ID actually prevents the cache from actually caching requests. Which is kind of a problem ;)

**Comment by csarrazi** [comment]
Keep in mind that not adding the `on_stats` option for fetching the various request stats is only a temporary fix, until the issue is fixed in guzzle.

**Comment by jderusse** [comment]
What if, instead of using headers to store the correlationId, we directly set a property in the reaquest object. 
It's more dirty from a POO point of view. But headers shouldn't change and cache should works again.

**Comment by csarrazi** [comment]
Like you said, it would be even dirtier

**Comment by csarrazi** [comment]
Also, as I mentioned earlier, we definitely don't have any useful stats in the stream handler, so that's the best way to deal with the problem.

**Pull request merged**
