### PR TITLE
Add domain name in recorded mock file name.

### PR DESCRIPTION
**Pull request by Torgan**

### CODE REVIEW

**Comment by csarrazi** [comment]
Could you fix the tests please ? Thanks ! :)

**Comment by Torgan** [comment]
I have been unable to launch the tests so far :|

**Comment by csarrazi** [comment]
You simply need to go in the bundle's directory (`vendor/csa/guzzle-bundle`), run `composer install`, and then run `vendor/bin/phpunit`. :)

**Comment by Torgan** [comment]
Thanks, figured that out, fix is coming.

**Comment by csarrazi** [comment]
As we want to prevent BC, we should check whether the file exists

* without a host
* with a host

The latter being preferred, of course.

**Comment by csarrazi** [comment]
LGTM! :+1:

**Comment by csarrazi** [comment]
Thanks @Torgan ! :smiley:

**Pull request merged**
