### PR TITLE
Suggest tolerance/tolerance

### PR DESCRIPTION
**Pull request by iamluc**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #191 
| License       | Apache License 2.0

### CODE REVIEW

**Comment by csarrazi** [comment]
👍 

This PR should rather be done against the 2.x branch. If you don't have time to change the target branch for your PR, I'll merge your changes in the `2.x` branch then `master` and close your PR during the week-end.

**Comment by csarrazi** [comment]
By the way, the lock file should probably be updated. You can update the lock file (without changing the dependencies) using the `composer update --lock` command.

**Comment by iamluc** [comment]
Indeed, I didn't see the `composer.lock` file.
But IMHO, it is useless for a bundle and should be removed.

**Comment by csarrazi** [comment]
I do agree, but this is actually a requirement for most static analysis tools (insight and scrutinizer).

**Comment by iamluc** [comment]
Updated !

**Comment by csarrazi** [comment]
Thanks @iamluc!

**Pull request merged**
