### PR TITLE
Fix mock with long urls

### PR DESCRIPTION
**Pull request by SiM07**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #130 
| License       | MIT

I'm not really satisfy by the result because it's difficult to identify wich url match with a file. It's useful when we record with phpunit.

I'm not use the same [algorithm as doctrine cache](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/FileCache.php#L142) because it does not produce the same result on windows or unix. Windows and it's maxpath and specials chars in filename ...

### CODE REVIEW

**Comment by csarrazi** [comment]
This introduces a BC break. We need to keep compatibility with previous versions.

Also, we should make sure that we have something which is a bit more readable. I would recommend we keep the hostname and path parts of the request, in order to be able to identify the mock file easily.

What I mean is that we only need to hash the bigger and more dynamic parameters (i.e. headers, body and query params).

**Comment by SofHad** [comment]
What about adding the ability to configure this?
Like this for example: 
```yml
# config_test.yml
csa_guzzle:
    mock:
        storage_path: "%kernel.root_dir%/../features/fixtures/guzzle"
        mode: record
        path_generator: service_id  # default: we keep compatibility with previous versions
```

**Comment by SiM07** [comment]
Yes it's a good idea or simpler create a windows compatibility flag where the regex remove char like `?` and create shorter files.

**Comment by csarrazi** [comment]
Unfortunately this is still a no-go.

Often, people working on a project do not necessarily have the same OS, and may use Windows as well as OSX or even vagrant.

If the strategy is different for each OS, this means that if someone generated the fixtures from Windows won't be able to use the fixtures on his Mac or on his Linux environment.

**Comment by csarrazi** [comment]
Also we do not want someone using a strategy which won't work on another environment.

**Comment by SiM07** [comment]
I'm agree and this configuration must be in config.yml and static. Today [this regex](https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/GuzzleHttp/Cache/MockStorageAdapter.php#L139) can't produce correct file on Windows because it allow question mark.

**Comment by csarrazi** [comment]
True. However if by question mark you are speaking about the query separator, it is already handled a few lines before. Maybe we can ask @iamluc for more information regarding that matter.

**Comment by csarrazi** [comment]
Closing in favour of #135.

**Pull request closed without merging**
