### PR TITLE
Added class in DefinitionDecorator, as it breaks with Symfony < 2.8.

### LINKED ISSUE #118: 2.0.4 is broken when using Symfony 2.7
When Symfony 2.7 is used, the PHP dump container is invalid. This happens when no handler waas provided to any client. Using Symfony 2.8.1, the container is valid (maybe 2.8.0 is working too, but I haven't tested it).

I originaly reported the issue in https://github.com/symfony/symfony/issues/17353.

Probably the minimum version of `symfony/dependency-injection` should be `^2.8|^3.0`

### PR DESCRIPTION
**Pull request by csarrazi**
Fixes #118

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1: looks weird to me that this works without any issue on Symfony 2.8

**Comment by csarrazi** [comment]
@xabbuh Indeed, this is really, really weird...

**Comment by jakzal** [comment]
The reason for this is [2.7 ignores abstract definitions](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionTemplatesPass.php#L46), while [2.8 does not](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/DependencyInjection/Compiler/ResolveDefinitionTemplatesPass.php#L42). The change was introduced in https://github.com/symfony/symfony/pull/15096.

**Comment by csarrazi** [comment]
Thanks @jakzal!

**Pull request merged**
